# Generated by Django 3.2.7 on 2021-10-06 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('pet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('pet_age', models.CharField(max_length=20, verbose_name='edad')),
                ('pet_color', models.CharField(max_length=20, verbose_name='color')),
                ('pet_type', models.CharField(max_length=20, verbose_name='tipo')),
                ('pet_size', models.CharField(max_length=20, verbose_name='tamaño')),
                ('pet_image', models.CharField(max_length=100, verbose_name='imagen')),
                ('pet_description', models.CharField(max_length=100, verbose_name='descripción')),
                ('pet_status', models.CharField(default='Pendiente', max_length=20, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=30, verbose_name='nombre_solicitante')),
                ('applicant_last_name', models.CharField(max_length=30, verbose_name='apellido_solicitante')),
                ('document_id', models.CharField(max_length=20, verbose_name='documento')),
                ('applicant_age', models.CharField(max_length=3, verbose_name='edad_solicitante')),
                ('address', models.CharField(max_length=100, verbose_name='direccion')),
                ('phone', models.CharField(max_length=30, verbose_name='telefono')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('income', models.IntegerField(verbose_name='ingresos')),
                ('activity', models.CharField(max_length=30, verbose_name='actividad_economica')),
                ('reason', models.CharField(max_length=100, verbose_name='motivo_adopcion')),
                ('request_status', models.CharField(max_length=30, verbose_name='estado')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.petmodel')),
            ],
        ),
    ]
